String saveCacheDirectory = "/data/user/0/com.thrill/cache/";               //sound will be downloaded here
String saveDirectory = "/storage/emulated/0/Download/";                     //unposted videos will be stored here (posted/draft videos gets deleted from device)
const admobAppId = "ca-app-pub-3940256099942544~3347511713";                      //replace this with live and also change in Android Manifest
const homeInterstitialAdUnit = "ca-app-pub-3940256099942544/1033173712";          //this is test id, replace with live

const String login = 'LOG IN';
const String mobileNumber = 'Mobile Number';
const String password = 'Password';
const String forgotPassword = 'Forgot M-PIN';
const String dontHaveAnAccount = "Don't have an account? ";
const String signUp = "Sign Up";
const String createAnAccount = "CREATE AN ACCOUNT";
const String doYouHaveAnAccount = "Do you have an account? ";
const String logIn = "Log In";
const String fullName = "Full Name";
const String birthday = "Birthday";
const String following = "Following";
const String followers = "Followers";
const String likes = "Likes";
const String related = "Related";
const String liveUsers = "Popular";
const String leaveAComment = "Leave a comment...";
const String search = "Search";
const String notifications = "Notifications";
const String watch = "Watch";
const String level = "Level";
const String editProfile = "Edit Profile";
const String inviteUser = "Invite User";
const String wallet = "Wallet";
const String userReferralCount = "User Referral Count :- ";
const String availableBalance = "Available Balance";
const String availableBalanceDollar = "Available Balance in Dollar";
const String availableBalanceEuro = "Available Balance in Euro";
const String availableBalanceSar = "Available Balance in SAR";
const String withdrawAmount = "Withdraw Amount";
const String history = "History";
const String paytm = "PayTM";
const String referral = "Referral";
const String referNow = "Refer Now";
const String totalReferral = "Total Referral";
const String referMoreEarnMore = "Refer more to earn more!";
const String referMoreEarnMoreDialog =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.";
const String yourReferralCode = "Your Referral Code";
const String iAgreeToThe = "I agree to the ";
const String privacyPolicy = "Privacy Policy";
const String earnSpins = "Earn Spins";
const String levelForCreators = "Level for Creators";
const String levelForViewers = "Level for Viewers";
const String levelForReferral = "Level for Referral";
const String earnedSpins = "Earned Spins: ";
const String spinWheel = "Spin Wheel";
const String earnSpinDialog =
    "Get 15M total likes (current month from 1st date to last)";
const String spinTheWheel = 'Spin The Wheel!';
const String eventClosingIn = "Event closing in";
const String availableChange = "Available Chance";
const String grabExtensiveRewards = "Grab Extensive Rewards";
const String usedChance = "Used Chance";
const String lastReward = "Last Reward";
const String addSound = "Add Sound";
const String upload = "Upload";
const String post = "Post";
const String describeYourVideo = "Describe your video";
const String hashtags = "#Hashtags";
const String friends = "@Friends";
const String whoCanViewThisVideo = "Who can view this video";
const String public = "Public";
const String private = "Private";
const String allowComments = "Allow Comments";
const String allowDuets = "Allow Duets";
const String draft = "Draft";
const String postVideo = "Post Video";
const String videos = "Videos";
const String addedToFavourite = "Added To Favourite";
const String favourites = "Favourites";
const String sounds = "Sounds";
const String hashTag = "HashTag";
const String whoops = "Whoops!";
const String originalSound = "Original sound - ";
const String save = "Save";
const String create = "Create";
const String inbox = "Inbox";
const String message = "Message";
const String sendTo = "Send to";
const String shareTo = "Share to";
const String settingAndPrivacy = "Setting and Privacy";
const String account = "ACCOUNT";
const String manageAccount = "Manage Account";
const String privacy = "Privacy";
const String requestVerification = "Request Verification";
const String qrCode = "QR Code";
const String shareProfile = "Share Profile";
const String myTeam = "My Team";
const String pushNotification = "Push Notification";
const String appLanguage = "App Language";
const String english = "English";
const String contentAndActivity = "CONTENT & ACTIVITY";
const String cacheAndCellularData = "CACHE & CELLULAR DATA";
const String about = "ABOUT";
const String freeUpSpace = "Free up space";
const String termsOfService = "Terms of Service";
const String technicalSupport = "Technical Support";
const String switchAccount = "Switch Account";
const String logout = "Logout";
const String accountControl = "ACCOUNT CONTROL";
const String accountDetails = "personal information";
const String deactivateAccount = "Deactivate Account";
const String applyForVerification = "Apply for Sr Shorts Verification";
const String username = "Username";
const String chooseFile = "Choose File";
const String send = "SEND";
const String safety = "Safety";
const String allowYourVideosToBeDownloaded =
    "Allow your videos to be Downloaded";
const String allowYourVideosToBeDownloadedDialog =
    "Choose option, if you want anyone can download your videos";
const String on = "ON";
const String whoCanSendYouDirectMessage = "Who can send you direct Messages";
const String whoCanSendYouDirectMessageDialog =
    "Choose option, if you want anyone can send you messages directly";
const String everyone = "EVERYONE";
const String me = "ME";
const String whoCanDuetWithYourVideo = "Who can Duet with your Videos";
const String whoCanDuetWithYourVideoDialog =
    "Choose option, if you want anyone can make duet video with your video";
const String whoCanViewYourLikedVideos = "Who can view your Liked Videos";
const String whoCanViewYourLikedVideosDialog =
    "Choose option, if you want anyone can view your likes on a video";
const String whoCanCommentOnYourVideos = "Who can Comment on your Videos";
const String whoCanCommentOnYourVideosDialog =
    "Choose option, if you want anyone can comment on your videos";
const String saveToDevice = 'Save to Device';
const String scanQRCode = 'Scan QR Code';
const String interactions = 'Interactions';
const String comments = 'Comments';
const String newFollowers = 'New Followers';
const String mentions = 'Mentions';
const String directMessages = 'Direct Messages';
const String videoUpdates = 'Video Updates';
const String chooseToReceivePushNotificationOnLike =
    'Choose if you like to receive push notification on every like';
const String chooseToReceivePushNotificationOnComment =
    'Choose if you like to receive push notification on every comment';
const String chooseToReceivePushNotificationNewFollower =
    'Choose if you like to receive push notification on every new follower';
const String chooseToReceivePushNotificationMentions =
    'Choose if you like to receive push notification when someone mention you on his/her post';
const String chooseToReceivePushNotificationDirectMessage =
    'Choose if you like to receive push notification when someone send you direct message';
const String chooseToReceivePushNotificationVideoUpdates =
    'Choose if you like to receive push notification when someone on your following list post new video';
const String cache = 'Cache : ';
const String clear = 'Clear';
const String download = 'Download : ';
const String clearCacheDialog =
    "Clear your cache to free up space. This won't effect your app experience.";
const String clearDownloadDialog =
    "Download me include effects, filter stickers, and virtual gifts downloaded in your app. You'll be able to download them again if you need them.";
const String customerSupport = 'Customer Support';
const String howCanWeHelpYou = 'How can we help you?';
const String callUs = 'Call Us';
const String emailUs = 'Email Us';
const String firstName = 'First Name';
const String lastName = 'Last Name';
const String gender = 'Gender';
const String websiteURL = 'Website URL';
const String yourBio = 'Your bio';
const String linkSocialAccounts = 'Link Social Accounts';
const String male = 'Male';
const String female = 'Female';
const String other = 'Other';
const String linkYouTube = 'Link your YouTube to\nyour Profile bio.';
const String linkFacebook = 'Link your Facebook to\nyour Profile bio.';
const String linkInstagram = 'Link your Instagram to\nyour Profile bio.';
const String linkTwitter = 'Link your Twitter to\nyour Profile bio.';
const String youtubeURL = 'www.youtube.com/';
const String facebookURL = 'www.facebook.com/';
const String instagramURL = 'www.instagram.com/';
const String twitterURL = 'www.twitter.com/';
const String cancel = 'Cancel';
const String whatsApp = 'WhatsApp';
const String facebook = 'Facebook';
const String messenger = 'Messenger';
const String sms = 'SMS';
const String copyLink = 'Copy Link';
const String report = 'Report';
const String block = 'Block';
const String sendMessage = 'Send Message';
const String discover = 'Discover';
const String myFavourites = 'My Favourites';
const String newSong = 'New Song';
const String addAccount = 'Add Account';
const String paymentHistory = 'Payment History';
const String type = 'Type...';
const String exitDialog = 'Do you really want to Exit ?';
const String closeDialog = 'Do you really want to Go Back ?';
const String discardDialog = 'Any changes made will be discarded!';
const String yes = 'Yes';
const String no = 'No';
const String ok = 'OK';
const String failed = 'Failed!';
const String successful = 'Successful!';
const String chooseFromDevice = "Choose From Device";
const String noSoundFound = "No Sound Found!";
const String chooseMusic = "Choose Music";
