name: thrill
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.2 <3.0.0'

dependencies: 
  sqflite: any
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  firebase_messaging: ^14.1.4
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6
  image_picker: ^0.8.6
  visibility_detector: ^0.3.3
  camera: ^0.10.3
  path_provider: ^2.0.11
  simple_s3: any
  flutter_fortune_wheel: any
  audioplayers: any
  file_support: any
  ffmpeg_kit_flutter_full_gpl: any
  video_player: any
  qr_flutter: any
  flutter_svg: any
  syncfusion_flutter_sliders: any
  file_picker: any
  share_plus: any
  preload_page_view: any
  url_launcher: any
  google_mobile_ads: any
  firebase_database: any
  awesome_notifications: any
  flutter_barcode_scanner: ^2.0.0
  pin_code_fields: any
  permission_handler: any
  glassmorphism_ui: any
  get: any
  persistent_bottom_nav_bar: any
  video_editor_sdk: ^2.7.1
  carousel_indicator: any
  external_path: any
  flutter_staggered_grid_view: any
  animated_segmented_tab_control: any
  iconly: any
  animated_button_bar: any
  showcaseview: any
  get_storage: any
  gallery_saver: any
  just_audio: any
  multi_select_flutter: any
  hashtagable: any
  firebase_dynamic_links: ^5.0.8
  truecaller_sdk: ^0.1.2
  dio: any
  lottie: ^1.4.3
  audio_video_progress_bar: ^0.11.0
  glassmorphism: ^3.0.0
  path: ^1.8.2
  on_audio_query: ^2.8.1
  flutter_switch: ^0.3.2
  webview_flutter: ^4.0.6
  audio_waveforms: ^0.1.5+1
  image_cropper: ^3.0.1
  otp_autofill: ^2.1.0
  sms_autofill: ^2.2.0
  flutter_datetime_picker: ^1.5.1
  like_button: ^2.0.5
  flutter_chat_ui: ^1.6.6
  flutter_firebase_chat_core: ^1.6.4
  cloud_firestore: ^4.3.1
  icons_plus: ^4.0.0
  logger: ^1.1.0
  sim_data: ^0.0.2
  uri_to_file: ^0.2.0
  adaptive_theme: ^3.1.1
  web_socket_channel: ^2.3.0
  flutter_animation_progress_bar: ^2.3.1
  inview_notifier_list: ^3.0.0
  network_info_plus: ^3.0.2
  mac_address: ^1.0.0
  flutter_html: ^3.0.0-alpha.6
  animated_bottom_navigation_bar: ^1.1.0+1
  amazon_cognito_identity_dart_2: ^3.2.0
  double_back_to_close: ^2.0.0
  flutter_neumorphic: ^3.2.0
  tiktoklikescroller: ^0.2.3
  device_info_plus: ^8.2.2
  video_thumbnail: ^0.5.3
  flutter_video_info: ^1.3.1
  torch_light: ^1.0.0
  video_compress: ^3.1.2
  connectivity_plus: ^4.0.1
  flutter_otp_text_field: ^1.1.1
  loop_page_view: ^1.2.1
  flutter_local_notifications: 14.1.1
  flutter: 
    sdk: flutter
  better_player: 
    git: https://github.com/tintran-dev/betterplayer.git
  readmore: ^2.2.0
  flutter_native_splash: ^2.2.19


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: fonts/Urbanist.ttf
        - asset: fonts/Urbanist-Bold.ttf
        - asset: fonts/Urbanist-Italic.ttf
    - family: Abel
      fonts: 
        - asset: fonts/Abel-Regular.ttf
    - family: Quicksand
      fonts: 
        - asset: fonts/Quicksand-Regular.ttf
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Thin.ttf
  uses-material-design: true

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
#  color: "e1f5fe"
  background_image: "assets/spin_background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: "assets/spin_background.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  branding: "assets/logo2.png"

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
#  color_dark: "042a49"
#  background_image_dark: "assets/spin_background.png"
  # image_dark: assets/logo_lockup_flutter_vertical_wht.png
  branding_dark: "assets/logo2.png"

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
#    image: "assets/logo2.png"

  # Splash screen background color.
#    color: "42a5f5"

  # App icon background color.
    icon_background_color: "eeeeee"

  # The branding property allows you to specify an image used as branding in the splash screen.
  #branding: assets/dart.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  # apply when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
    #icon_background_color_dark: "#111111"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'